### ISSUE TITLE
Why not just make a plugin for flipper?

### ISSUE THREAD

**Issue by Pikaurd** [blankapp/flutter-debugger#4]
Nice work for flutter community.

I noticed this package based flipper I wonder to know why build a new app instead of a plugin?

Thank you.

**Comment by lijy91** [comment]
Because we need to package some custom flipper plugins (like [reduxinspector](https://github.com/blankapp/flipper-plugin-reduxinspector), [dbbrowser](https://github.com/blankapp/flipper-plugin-dbbrowser) or more), so that users can use some of our custom features more quickly.

https://github.com/facebook/flipper/issues/398

**Comment by lijy91** [comment]
You can use flipper desktop, but you need to follow the steps below to install our custom plugins.

Please see: https://github.com/facebook/flipper/issues/398#issuecomment-475099337
